### ISSUE TITLE
Tracking Issue: Invariant Test Ideas

### ISSUE THREAD

**Issue by apbendi** [uniswapfoundation/UniStaker#11]
- [ ] Total Supply is the same as:
    - [ ] Sum of all depositor totals
    - [ ] Sum of all earning power
    - [ ] Sum of all balances of all surrogates
